services:

  postgres:
    image: postgres:17
    container_name: ecommerce-db

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: ecommerce-backend

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: ecommerce

  frontend:
    build:
      context: ./frontend

    container_name: ecommerce-frontend

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  postgres_data:
